### ISSUE TITLE
MAGStock deployment should set use_checkin_barcode to False

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem-deploy#75]
Unless we plan on having barcode scanners at MAGStock?

I believe this involves adding the `use_checkin_barcode` setting in the following places:

```
# ubersystem-deploy/puppet/modules/uber/templates/uber-development.ini.erb
use_checkin_barcode = <%= @use_checkin_barcode %>
```

```
# ubersystem-deploy/puppet/modules/uber/manifests/config.pp
$use_checkin_barcode = true,
```

```
# ubersystem-deploy/puppet/hiera/nodes/event-magstock.yaml
uber::config::use_checkin_barcode: False
```

**Comment by RobRuana** [comment]
I've just realized that these changes need to be made in two other repos (no actual changes in this repo).

So this is really these two issues: 
1. `use_checkin_barcode` needs to be puppetized, see [#129](https://github.com/magfest/ubersystem-puppet/issues/129)
2. `use_checkin_barcode` should be `false` for magstock, see [#192](https://github.com/magfest/production-config/issues/192)

**Comment by kitsuta** [comment]
By the way, because we have so many repos, and because GitHub's auto-close syntax will work across repos (if you use "Fixes LINKTOISSUE" in the PR description), we're not too concerned about which repo an issue is in. If you find yourself accidentally filing an issue in the 'wrong' repo in the future, you can just cross-link it in the PR -- no need to close and re-file. We're all WAY too lazy for that. ;)
